dist: bionic
language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
    - python-gi                               # GObject
    - gir1.2-gtk-3.0                          # gi.repository.gtk
    - python-xdg                              # PyXDG
install:
  - pip install -r requirements_travis.txt
script:
  - python -m compileall .
  - flake8 .
  - python setup.py install --optimize=1 --root=build
  - ls -laR build
